//! mintpy-runner — MintPy stage dispatcher for the SISAR pipeline.
//!
//! Usage: mintpy-runner <stage_name>
//!
//! The runner receives a single snake_case MintPy stage name, executes the
//! corresponding smallbaselineApp.py step, and exits 0 on success or non-zero
//! on failure. All diagnostic output goes to stderr.
//!
//! Reads /job/specification.toml for job parameters (bounds, tropo method, etc.)
//! Results are written to /jobs/results/<job_id> as configured by the scheduler.

use anyhow::{bail, Context, Result};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus};

// ---------------------------------------------------------------------------
// Configuration types (from specification.toml)
// ---------------------------------------------------------------------------

#[derive(Debug, serde::Deserialize)]
struct Spec {
    folders: Folders,
    #[serde(rename = "mintpy")]
    mintpy: MintpyParams,
}

#[derive(Debug, serde::Deserialize)]
struct Folders {
    home: String,
}

#[derive(Debug, serde::Deserialize)]
struct MintpyParams {
    tropo: Option<String>,
}

// ---------------------------------------------------------------------------
// Valid MintPy stages (smallbaselineApp.py steps)
// ---------------------------------------------------------------------------

const VALID_STAGES: &[&str] = &[
    "load_data",
    "modify_network",
    "reference_point",
    "quick_overview",
    "correct_unwrap_error",
    "invert_network",
    "correct_lod",
    "correct_troposphere",
    "correct_topography",
    "residual_rms",
    "deramp",
    "correct_timeseries",
    "geocode",
    "google_earth",
    "hdfeos5",
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn run_cmd(program: &str, args: &[&str]) -> Result<ExitStatus> {
    eprintln!("[mintpy-runner] Running: {} {}", program, args.join(" "));
    let status = Command::new(program)
        .args(args)
        .status()
        .with_context(|| format!("Failed to spawn {program}"))?;
    Ok(status)
}

fn job_dir() -> PathBuf {
    PathBuf::from(std::env::var("JOB_DIR").unwrap_or_else(|_| "/jobs".into()))
}

fn results_dir() -> PathBuf {
    PathBuf::from(std::env::var("RESULTS_DIR").unwrap_or_else(|_| "/jobs/results".into()))
}

fn read_spec(job_dir: &Path) -> Result<Option<Spec>> {
    let spec_path = job_dir.join("specification.toml");
    if !spec_path.exists() {
        return Ok(None);
    }
    let raw = std::fs::read_to_string(&spec_path)
        .with_context(|| format!("Cannot read {}", spec_path.display()))?;
    let spec: Spec = toml::from_str(&raw)
        .with_context(|| format!("Cannot parse {}", spec_path.display()))?;
    Ok(Some(spec))
}

// ---------------------------------------------------------------------------
// Stage execution
// ---------------------------------------------------------------------------

/// Run a single smallbaselineApp.py step, outputting results to results_dir.
fn run_stage(stage: &str, job_dir: &Path, results_dir: &Path) -> Result<()> {
    // Ensure results directory exists
    std::fs::create_dir_all(results_dir)
        .with_context(|| format!("Cannot create {}", results_dir.display()))?;

    // smallbaselineApp.py --dir <results_dir> --dostep <stage>
    // It reads the template config from <results_dir>/smallbaselineApp.cfg
    // which must have been written on the load_data step (or pre-seeded).
    let results_str = results_dir.to_string_lossy();
    let status = run_cmd(
        "smallbaselineApp.py",
        &[
            "--dir", &results_str,
            "--dostep", stage,
        ],
    )?;

    if !status.success() {
        bail!(
            "smallbaselineApp.py --dostep {} exited with code {:?}",
            stage,
            status.code()
        );
    }

    Ok(())
}

/// Stage load_data additionally generates the smallbaselineApp.cfg from
/// specification.toml so the scheduler does not need to pre-seed it.
fn run_load_data(spec: &Option<Spec>, job_dir: &Path, results_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(results_dir)
        .with_context(|| format!("Cannot create {}", results_dir.display()))?;

    let cfg_path = results_dir.join("smallbaselineApp.cfg");

    // Only write config if it doesn't already exist (idempotent re-runs)
    if !cfg_path.exists() {
        let tropo_method = spec
            .as_ref()
            .and_then(|s| s.mintpy.tropo.as_deref())
            .unwrap_or("height_correlation");

        // mintpy.load.processor: isce  (outputs of sisar/isce2)
        // mintpy.load.unwFile pattern points at ISCE2 merged outputs
        let cfg = format!(
            r#"## Auto-generated by mintpy-runner — do not edit manually.
## Re-generated on each load_data invocation if absent.

mintpy.load.processor        = isce
mintpy.load.unwFile          = {job}/merged/interferograms/*/filt_*.unw
mintpy.load.corFile          = {job}/merged/interferograms/*/filt_*.cor
mintpy.load.connCompFile     = {job}/merged/interferograms/*/filt_*.unw.conncomp
mintpy.load.intFile          = None
mintpy.load.demFile          = {job}/merged/geom_reference/hgt.rdr
mintpy.load.lookupYFile      = {job}/merged/geom_reference/lat.rdr
mintpy.load.lookupXFile      = {job}/merged/geom_reference/lon.rdr
mintpy.load.incAngleFile     = {job}/merged/geom_reference/incLocal.rdr
mintpy.load.azAngleFile      = {job}/merged/geom_reference/azLocal.rdr
mintpy.load.shadowMaskFile   = {job}/merged/geom_reference/shadowMask.rdr

mintpy.troposphericDelay.method = {tropo}

mintpy.save.hdfEos5          = yes
mintpy.save.hdfEos5.update   = yes
"#,
            job = job_dir.display(),
            tropo = tropo_method,
        );

        std::fs::write(&cfg_path, cfg)
            .with_context(|| format!("Cannot write {}", cfg_path.display()))?;

        eprintln!(
            "[mintpy-runner] Written config: {}",
            cfg_path.display()
        );
    } else {
        eprintln!(
            "[mintpy-runner] Config exists, skipping generation: {}",
            cfg_path.display()
        );
    }

    run_stage("load_data", job_dir, results_dir)
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

fn dispatch(stage: &str, job_dir: &Path, results_dir: &Path) -> Result<()> {
    if !VALID_STAGES.contains(&stage) {
        bail!(
            "Unknown stage '{}'. Valid stages: {}",
            stage,
            VALID_STAGES.join(", ")
        );
    }

    let spec = read_spec(job_dir)?;

    if stage == "load_data" {
        run_load_data(&spec, job_dir, results_dir)
    } else {
        run_stage(stage, job_dir, results_dir)
    }
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

fn print_help() {
    eprintln!("mintpy-runner <stage_name>");
    eprintln!();
    eprintln!("Valid stages:");
    for s in VALID_STAGES {
        eprintln!("  {s}");
    }
    eprintln!();
    eprintln!("Environment variables:");
    eprintln!("  JOB_DIR      ISCE2 job directory  (default: /jobs)");
    eprintln!("  RESULTS_DIR  MintPy output dir    (default: /jobs/results)");
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 2 || args[1] == "--help" || args[1] == "-h" {
        print_help();
        std::process::exit(1);
    }

    let stage = &args[1];
    let job_dir = job_dir();
    let results_dir = results_dir();

    eprintln!("[mintpy-runner] Stage      : {stage}");
    eprintln!("[mintpy-runner] Job dir    : {}", job_dir.display());
    eprintln!("[mintpy-runner] Results dir: {}", results_dir.display());

    if let Err(e) = dispatch(stage, &job_dir, &results_dir) {
        eprintln!("[mintpy-runner] ERROR: {e:#}");
        std::process::exit(1);
    }

    eprintln!("[mintpy-runner] Stage '{stage}' completed successfully.");
}