//! mintpy-runner — MintPy stage dispatcher for the SISAR pipeline.
//!
//! Usage: mintpy-runner <stage_name>
//!
//! Receives a single snake_case MintPy stage name, changes into /job/series
//! (already done by entrypoint.sh, but asserted here for safety), then runs:
//!
//!     smallbaselineApp.py --dostep <stage> mintpy_params.cfg
//!
//! The config file /job/series/mintpy_params.cfg is expected to be
//! pre-generated by the scheduler. This binary does NOT generate it.
//!
//! Exit codes:
//!   0  — stage completed successfully
//!   1  — invalid usage, missing files, or smallbaselineApp.py failure

use anyhow::{bail, Context, Result};
use std::path::PathBuf;
use std::process::Command;

// ---------------------------------------------------------------------------
// Valid MintPy stages (smallbaselineApp.py --dostep values)
// Order matches the processing chain documented in entrypoint.sh.
// ---------------------------------------------------------------------------
const VALID_STAGES: &[&str] = &[
    "load_data",
    "modify_network",
    "reference_point",
    "quick_overview",
    "correct_unwrap_error",
    "invert_network",
    "correct_LOD",
    "correct_SET",
    "correct_ionosphere",
    "correct_troposphere",
    "deramp",
    "correct_topography",
    "residual_RMS",
    "reference_date",
    "velocity",
    "geocode",
    "google_earth",
    "hdfeos5",
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Returns the series directory: $JOB_DIR/series, defaulting to /job/series.
fn series_dir() -> PathBuf {
    let job_dir = std::env::var("JOB_DIR").unwrap_or_else(|_| "/job".into());
    PathBuf::from(job_dir).join("series")
}

/// Asserts that the process working directory is the series directory.
/// entrypoint.sh already does `cd`, but we verify to catch mis-invocations.
fn assert_cwd_is_series(series: &PathBuf) -> Result<()> {
    let cwd = std::env::current_dir().context("Cannot determine current working directory")?;
    // Canonicalise both paths so symlinks / trailing slashes don't cause false
    // negatives. Fall back to a string comparison if canonicalisation fails
    // (e.g. the directory does not exist yet — handled below).
    let cwd_canon = cwd.canonicalize().unwrap_or(cwd.clone());
    let series_canon = series.canonicalize().unwrap_or(series.clone());
    if cwd_canon != series_canon {
        bail!(
            "Working directory mismatch.\n  expected: {}\n  actual  : {}\n\
             smallbaselineApp.py must be run from the series directory.",
            series.display(),
            cwd.display()
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Stage execution
// ---------------------------------------------------------------------------

fn run_stage(stage: &str) -> Result<()> {
    let series = series_dir();

    // Verify working directory
    if !series.is_dir() {
        bail!("Series directory not found: {}", series.display());
    }
    assert_cwd_is_series(&series)?;

    // Verify config file
    let cfg = series.join("mintpy_params.cfg");
    if !cfg.is_file() {
        bail!(
            "mintpy_params.cfg not found: {}\n\
             The scheduler must pre-generate this file before launching the container.",
            cfg.display()
        );
    }

    // Build command:  smallbaselineApp.py --dostep <stage> mintpy_params.cfg
    eprintln!(
        "[mintpy-runner] Running: smallbaselineApp.py --dostep {} mintpy_params.cfg",
        stage
    );

    let status = Command::new("smallbaselineApp.py")
        .args(["--dostep", stage, "mintpy_params.cfg"])
        .status()
        .context("Failed to spawn smallbaselineApp.py — is MintPy installed?")?;

    if !status.success() {
        bail!(
            "smallbaselineApp.py --dostep {} exited with code {:?}",
            stage,
            status.code()
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

fn print_help() {
    eprintln!("mintpy-runner <stage_name>");
    eprintln!();
    eprintln!("Runs: smallbaselineApp.py --dostep <stage_name> mintpy_params.cfg");
    eprintln!("Must be invoked from /job/series (handled by entrypoint.sh).");
    eprintln!();
    eprintln!("Valid stages:");
    for s in VALID_STAGES {
        eprintln!("  {s}");
    }
    eprintln!();
    eprintln!("Environment variables:");
    eprintln!("  JOB_DIR   job root directory (default: /job)");
    eprintln!("            series dir = $JOB_DIR/series");
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 2 || args[1] == "--help" || args[1] == "-h" {
        print_help();
        std::process::exit(if args.len() < 2 { 1 } else { 0 });
    }

    let stage = &args[1];

    if !VALID_STAGES.contains(&stage.as_str()) {
        eprintln!(
            "[mintpy-runner] ERROR: Unknown stage '{stage}'.\nValid stages: {}",
            VALID_STAGES.join(", ")
        );
        std::process::exit(1);
    }

    eprintln!("[mintpy-runner] stage: {stage}");
    eprintln!("[mintpy-runner] series dir: {}", series_dir().display());

    if let Err(e) = run_stage(stage) {
        eprintln!("[mintpy-runner] ERROR: {e:#}");
        std::process::exit(1);
    }

    eprintln!("[mintpy-runner] stage '{stage}' completed successfully.");
}
