[folders]
home="/job"
data="/job/data"
orbits="/job/orbits"
dem="/job/dem"
aux="/job/aux"
weather="/job/weather"

[dem.bounds]
south=-38.05
north=-37.85
west=-69.55
east=-69.35

[download]
start="2024-01-01"
end="2024-01-10"

[isce]
range_looks=20
azimuth_looks=5
connections=2
virtual=true

[processing.bounds]
south=-38.05
north=-37.85
west=-69.55
east=-69.35

[mintpy]
tropo="height_correlation"